RepoMaker/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from maker.views import media_serve
from maker.views.repository import RepositoryListView

urlpatterns = [
    url(r'^$', RepositoryListView.as_view(), name="index"),
    url(r'^repo/', include('maker.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], media_serve,
        {'document_root': settings.MEDIA_ROOT}),
]

if not settings.SINGLE_USER_MODE:
    urlpatterns += [
        url(r'^accounts/', include('allauth.urls')),
    ]

maker/urls.py
from django.conf.urls import url

from maker.models import S3Storage, SshStorage, GitStorage
from maker.views.app import AppCreateView, AppDetailView, AppUpdateView, AppDeleteView, \
    AppTranslationUpdateView
from maker.views.gitstorage import GitStorageCreate, GitStorageUpdate, GitStorageDetail, \
    GitStorageDelete
from maker.views.remoterepository import RemoteRepositoryCreateView, RemoteAppCreateView
from maker.views.repository import RepositoryListView, RepositoryCreateView, RepositoryDetailView
from maker.views.s3storage import S3StorageCreate, S3StorageUpdate, S3StorageDelete
from maker.views.screenshot import ScreenshotCreateView, ScreenshotDeleteView
from maker.views.sshstorage import SshStorageCreate, SshStorageUpdate, SshStorageDetail, \
    SshStorageDelete
from . import views


urlpatterns = [
    # Repo
    url(r'^$', RepositoryListView.as_view(), name='index'),
    url(r'^add$', RepositoryCreateView.as_view(), name='add_repo'),
    url(r'^(?P<repo_id>[0-9]+)/$', RepositoryDetailView.as_view(), name='repo'),

    # Remote Repo
    url(r'^remote/add$', RemoteRepositoryCreateView.as_view(), name='add_remote_repo'),
    url(r'^remote/(?P<remote_repo_id>[0-9]+)/update/$', views.remote_update, name='remote_update'),

    # App
    url(r'^(?P<repo_id>[0-9]+)/app/add/$', AppCreateView.as_view(), name='add_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/remote/(?P<remote_repo_id>[0-9]+)/add/$',
        AppCreateView.as_view(), name='add_app_from_remote'),
    url(r'^(?P<repo_id>[0-9]+)/app/remote/(?P<remote_repo_id>[0-9]+)/add/(?P<app_id>[0-9]+)$',
        RemoteAppCreateView.as_view(), name='add_remote_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/$', AppDetailView.as_view(), name='app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/edit/$', AppUpdateView.as_view(),
        name='edit_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/delete/$', AppDeleteView.as_view(),
        name='delete_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/translate/$',
        AppTranslationUpdateView.as_view(), name='app_translate'),

    # App Screenshots
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/screenshot/add/$',
        ScreenshotCreateView.as_view(), name='screenshot_add'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/screenshot/(?P<s_id>[0-9]+)/delete/$',
        ScreenshotDeleteView.as_view(), name='screenshot_delete'),

    # Repo Operations
    url(r'^(?P<repo_id>[0-9]+)/update/$$', views.update, name='update'),
    url(r'^(?P<repo_id>[0-9]+)/publish/$$', views.publish, name='publish'),

    # SSH Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/add/$',
        SshStorageCreate.as_view(), name='storage_ssh_add'),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/$',
        SshStorageUpdate.as_view(), name=SshStorage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/detail$',
        SshStorageDetail.as_view(), name='storage_ssh_detail'),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/delete/$',
        SshStorageDelete.as_view(), name=SshStorage.delete_url_name),

    # Git Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/git/add/$',
        GitStorageCreate.as_view(), name='storage_git_add'),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/$',
        GitStorageUpdate.as_view(), name=GitStorage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/detail$',
        GitStorageDetail.as_view(), name='storage_git_detail'),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/delete/$',
        GitStorageDelete.as_view(), name=GitStorage.delete_url_name),

    # S3 Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/add/$',
        S3StorageCreate.as_view(), name='storage_s3_add'),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/$',
        S3StorageUpdate.as_view(), name=S3Storage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/delete/$',
        S3StorageDelete.as_view(), name=S3Storage.delete_url_name),
]

maker/models/category.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=64)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name_plural = "Categories"
        unique_together = (("user", "name"),)

maker/models/screenshot.py
import logging
import os
from io import BytesIO

import requests
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

from maker import tasks
from maker.storage import get_screenshot_file_path, RepoStorage
from .app import RemoteApp, App

PHONE = 'phoneScreenshots'
SEVEN_INCH = 'sevenInchScreenshots'
TEN_INCH = 'tenInchScreenshots'
TV = 'tvScreenshots'
WEAR = 'wearScreenshots'
TYPE_CHOICES = (
    (PHONE, 'Phone'),
    (SEVEN_INCH, "7'' Tablet"),
    (TEN_INCH, "10'' Tablet"),
    (TV, 'TV'),
    (WEAR, 'Wearable'),
)


class AbstractScreenshot(models.Model):
    language_code = models.CharField(max_length=32, default='en')
    type = models.CharField(max_length=32, choices=TYPE_CHOICES, default=PHONE)

    def __str__(self):
        return self.app.__str__() + " - " + self.language_code + " " + self.type

    def get_url(self):
        raise NotImplementedError()

    class Meta:
        abstract = True


class Screenshot(AbstractScreenshot):
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_screenshot_file_path, storage=RepoStorage(),
                            max_length=1024)
    # TODO add a thumbnail to be automatically generated from file

    def __str__(self):
        return super(Screenshot, self).__str__() + " " + self.file.name

    def get_relative_path(self):
        return os.path.join(self.app.package_id, self.language_code, self.type)

    def get_url(self):
        return self.file.url


class RemoteScreenshot(AbstractScreenshot):
    app = models.ForeignKey(RemoteApp, on_delete=models.CASCADE)
    url = models.URLField(max_length=2048)

    def __str__(self):
        return super(RemoteScreenshot, self).__str__() + " " + os.path.basename(self.url)

    def get_url(self):
        return self.url

    @staticmethod
    def add(locale, s_type, app, base_url, files):
        """
        Creates and saves one or more new RemoteScreenshots if the given s_type is supported.
        """
        if not is_supported_type(s_type):
            return
        for file in files:
            url = base_url + '/' + file
            if not RemoteScreenshot.objects.filter(language_code=locale, type=s_type, app=app,
                                                   url=url).exists():
                screenshot = RemoteScreenshot(language_code=locale, type=s_type, app=app, url=url)
                screenshot.save()

    def download_async(self, app):
        """
        Downloads this RemoteScreenshot asynchronously and creates a local Screenshot if successful.
        """
        tasks.download_remote_screenshot(self.pk, app.pk)

    def download(self, app_id):
        """
        Does a blocking download of this RemoteScreenshot
        and creates a local Screenshot if successful.
        """
        screenshot = Screenshot(language_code=self.language_code, type=self.type, app_id=app_id)
        r = requests.get(self.url)
        if r.status_code == requests.codes.ok:
            screenshot.file.save(os.path.basename(self.url), BytesIO(r.content), save=True)


def is_supported_type(s_type):
    for t in TYPE_CHOICES:
        if s_type == t[0]:
            return True
    return False


@receiver(post_delete, sender=Screenshot)
def screenshot_post_delete_handler(**kwargs):
    apk = kwargs['instance']
    logging.info("Deleting Screenshot: %s", apk.file.name)
    apk.file.delete(save=False)

maker/views/gitstorage.py
import fdroidserver.index
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.forms import CharField, URLField
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView

from maker.models.storage import GitStorage, HostnameValidator, PathValidator
from .sshstorage import SshStorageForm, SshKeyMixin
from .storage import StorageCreateView, StorageUpdateView, StorageDeleteView


class GitStorageForm(SshStorageForm):
    ssh_url = CharField(required=True, label=_('Git Repository SSH Address'))
    url = URLField(required=False, label=_('Raw Git URL'), help_text=_(
        'This is the location where the uploaded files can be accessed from' +
        ' in raw form.' +
        ' Leave empty for GitHub or GitLab.com repositories.'))

    def get_initial_for_field(self, field, field_name):
        if field_name == 'ssh_url' and self.instance.pk:
            return self.instance.get_remote_url()
        return super(GitStorageForm, self).get_initial_for_field(field, field_name)

    class Meta(SshStorageForm.Meta):
        model = GitStorage
        fields = ['ssh_url', 'url']


class GitUrlValidationMixin(SshKeyMixin):

    def form_valid(self, form):
        # check that ssh_url starts with git@
        if not form.cleaned_data['ssh_url'].startswith('git@'):
            form.add_error('ssh_url', _("This URL must start with 'git@'."))
            return self.form_invalid(form)

        # strip the standard git user name from the URL
        ssh_url = form.cleaned_data['ssh_url'].replace('git@', '')

        # check that ssh_url ends with .git
        if not ssh_url.endswith('.git'):
            form.add_error('ssh_url', _("This URL must end with '.git'."))
            return self.form_invalid(form)

        # strip the .git ending from the URL
        ssh_url = ssh_url.replace('.git', '')

        # check that ssh_url includes a path
        url_error = _("This URL is invalid. Please copy the exact SSH URL of your git repository.")
        if ':' not in ssh_url:
            form.add_error('ssh_url', url_error)
            return self.form_invalid(form)

        # extract hostname and path from URL
        (hostname, path) = ssh_url.split(':', 1)

        # validate hostname and path
        try:
            HostnameValidator().__call__(hostname)
            PathValidator().__call__('/' + path)
        except ValidationError:
            form.add_error('ssh_url', url_error)
            return self.form_invalid(form)

        # assign hostname and path to the GitStorage object
        form.instance.host = hostname
        form.instance.path = path

        # try to generate the F-Droid repo URL from the git repo URL
        url = fdroidserver.index.get_raw_mirror(form.cleaned_data['ssh_url'])
        if url is not None:
            form.instance.url = url
        # URL generation failed, so the user needs to provide a valid URL
        else:
            try:
                URLValidator().__call__(form.cleaned_data['ssh_url'])
            except ValidationError:
                form.add_error('url', _('Please add a valid URL' +
                                        'for the raw content of this git repository.'))
                return self.form_invalid(form)

        return super(GitUrlValidationMixin, self).form_valid(form)


class GitStorageCreate(GitUrlValidationMixin, StorageCreateView):
    model = GitStorage
    form_class = GitStorageForm
    template_name = 'maker/storage/form_git.html'

    # TODO make adding a two step process,
    #      so the user can add the SSH key before an upload is attempted

    def get_success_url(self):
        self.get_repo().update_async()
        return reverse_lazy('storage_git_detail',
                            kwargs={'repo_id': self.kwargs['repo_id'], 'pk': self.object.pk})


class GitStorageUpdate(GitUrlValidationMixin, StorageUpdateView):
    model = GitStorage
    form_class = GitStorageForm

    def get_success_url(self):
        self.get_repo().update_async()
        return reverse_lazy('storage_git_detail',
                            kwargs={'repo_id': self.kwargs['repo_id'], 'pk': self.kwargs['pk']})


class GitStorageDetail(DetailView):
    model = GitStorage
    template_name = 'maker/storage/detail_git.html'


class GitStorageDelete(StorageDeleteView):
    model = GitStorage

maker/views/remoterepository.py
import urllib.parse

from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic.edit import CreateView
from fdroidserver import index

from maker.models import RemoteRepository, Repository, RemoteApp
from maker.views.repository import RepositoryAuthorizationMixin
from . import BaseModelForm, LoginOrSingleUserRequiredMixin


class RemoteRepositoryForm(BaseModelForm):
    class Meta:
        model = RemoteRepository
        fields = ['url']
        labels = {
            'url': _('Repository URL'),
        }


class RemoteRepositoryCreateView(LoginOrSingleUserRequiredMixin, CreateView):
    model = RemoteRepository
    form_class = RemoteRepositoryForm
    template_name = "maker/repo/add.html"

    def form_valid(self, form):
        user = self.request.user

        # ensure that URL contains a fingerprint
        url = urllib.parse.urlsplit(form.instance.url)
        query = urllib.parse.parse_qs(url.query)
        if 'fingerprint' not in query:
            form.add_error('url', _("Please use a URL with a fingerprint at the end" +
                           ", so we can validate the authenticity of the repository."))
            return self.form_invalid(form)

        # check if the user is trying to add their own repo here
        fingerprint = query['fingerprint'][0]
        if Repository.objects.filter(user=user, fingerprint=fingerprint).exists():
            form.add_error('url', _("Please don't add one of your own repositories here."))
            return self.form_invalid(form)

        # update URL and fingerprint to final values
        new_url = urllib.parse.SplitResult(url.scheme, url.netloc, url.path, '', '')
        form.instance.url = new_url.geturl()
        form.instance.fingerprint = fingerprint

        # check if this remote repo already exists and if so, re-use it
        existing_repo_query = RemoteRepository.objects.filter(url=form.instance.url,
                                                              fingerprint=fingerprint)
        # TODO also check if we maybe have a mirror of the repo already (maybe only use fingerprint)
        if existing_repo_query.exists():
            existing_repo = existing_repo_query.get()
            existing_repo.users.add(user)
            existing_repo.save()
            return HttpResponseRedirect(self.get_success_url())

        # download repo index and apply information to instance
        try:
            form.instance.update_index(update_apps=False)
            form.instance.update_async()  # schedule an async update for the apps as well
        except index.VerificationException as e:
            form.add_error('url', _("Could not validate repository: %s") % e)
            return self.form_invalid(form)

        result = super(RemoteRepositoryCreateView, self).form_valid(form)
        form.instance.users.add(user)
        form.instance.save()
        return result

    def get_success_url(self):
        # TODO point this to some sort of remote repo overview or detail view
        return reverse_lazy('index')


class RemoteAppCreateView(RepositoryAuthorizationMixin, CreateView):
    template_name = "maker/app/remote_add.html"
    fields = []
    object = None

    def get_queryset(self):
        remote_repo_id = self.kwargs['remote_repo_id']
        app_id = self.kwargs['app_id']
        return RemoteApp.objects.filter(repo__id=remote_repo_id,
                                        repo__users__id=self.request.user.id, pk=app_id)

    def get_context_data(self, **kwargs):
        context = super(RemoteAppCreateView, self).get_context_data(**kwargs)
        context['app'] = self.get_queryset().get()
        context['repo'] = self.get_repo()
        return context

    def form_valid(self, form):
        # ignore the form
        if not self.get_queryset().exists():
            return Http404()

        remote_app = self.get_queryset().get()
        self.object = remote_app.add_to_repo(self.get_repo())

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        # edit new app
        return reverse_lazy('app', kwargs={'repo_id': self.object.repo.pk,
                                           'app_id': self.object.pk})

maker/templates/maker/app/delete.html
{% extends "../base.html" %}
{% load i18n %}
{% load sass_tags %}

{% block title %}{% trans 'Delete App' %}{% endblock %}
{% block toolbar-title %}<a href="{% url 'repo' app.repo.id %}">{{ app.repo.name }}</a>{% endblock %}

{% block head %}
<link href="{% sass_src 'maker/css/forms.scss' %}" rel="stylesheet" type="text/css" media="all">
{% endblock head %}


{% block rm-content %}

<div class="rm-form">
    <form action="" method="post">
        {% csrf_token %}
        <p>{% blocktrans %}Are you sure you want to delete your app "{{ object }}"?{% endblocktrans %}</p>
        <div class="mdl-cell mdl-cell--6-col">
            <input type="submit" value="{% trans 'Confirm' %}"/>
        </div>
    </form>
</div>

{% endblock rm-content %}

maker/templates/maker/app/index.html
{% extends "../base.html" %}
{% load i18n %}
{% load humanize %}

{% block title %}{{ app.name }}{% endblock %}
{% block toolbar-title %}<a href="{% url 'repo' app.repo.id %}">{{ app.repo.name }}</a>{% endblock %}

{% block rm-content %}

<div class="mdl-grid">

	<div class="mdl-cell mdl-cell--12-col">

		<h2 style="vertical-align: middle;">
			<img src="{{ app.icon.url }}" alt="Repo Icon" class="rm-icon"/> {{ app.name }}
		</h2>

		{% if app.summary %}
		<p>{{ app.summary }}</p>
		{% endif %}

		<ul class="mdl-list">
			<li class="mdl-list__item mdl-list__item--two-line">
				<span class="mdl-list__item-primary-content">
					<i class="material-icons mdl-list__item-icon">info_outline</i>
					<span>{% trans 'Package ID' %}</span>
					<span class="mdl-list__item-sub-title">
						{{ app.package_id }}
					</span>
				</span>
			</li>
			<li class="mdl-list__item mdl-list__item--two-line">
				<span class="mdl-list__item-primary-content">
					<i class="material-icons mdl-list__item-icon">style</i>
					<span>{% trans 'Categories' %}</span>
					<span class="mdl-list__item-sub-title">
						{% if app.category.exists %}
						{{ app.category.all|join:", " }}
						{% else %}
						None
						{% endif %}
					</span>
				</span>
			</li>
			{% if app.website %}
			<li class="mdl-list__item mdl-list__item--two-line">
				<span class="mdl-list__item-primary-content">
					<i class="material-icons mdl-list__item-icon">insert_link</i>
					<span>{% trans 'Website' %}</span>
					<span class="mdl-list__item-sub-title">
						{{ app.website|urlize }}
					</span>
				</span>
			</li>
			{% endif %}
			{% if app.description %}
			<li class="mdl-list__item mdl-list__item--three-line">
				<span class="mdl-list__item-primary-content">
					<i class="material-icons mdl-list__item-icon">description</i>
					<span>{% trans 'Description' %}</span>
					<span class="mdl-list__item-text-body">
						{{ app.description|safe }}
					</span>
				</span>
			</li>
			{% endif %}
			<li class="mdl-list__item mdl-list__item--two-line">
				<span class="mdl-list__item-primary-content">
					<i class="material-icons mdl-list__item-icon">translate</i>
					<span>{% trans 'Translations' %}</span>
					<span class="mdl-list__item-sub-title">
						{% for lang in app.get_available_languages %}
							{{ lang|language_name }}{% if not forloop.last %}, {% endif %}
							{% empty %}
							<i>{% trans 'None' %}</i>
						{% endfor %}
					</span>
				</span>
				<span class="mdl-list__item-secondary-content">
					<a class="mdl-list__item-secondary-action" href="{% url 'app_translate' app.repo.id app.id %}">
						<i class="material-icons">edit</i>
					</a>
				</span>
			</li>
			{% if apks %}
			<li class="mdl-list__item mdl-list__item--two-line">
				<span class="mdl-list__item-primary-content">
					<i class="material-icons mdl-list__item-icon">gesture</i>
					<span>{% trans 'Signature' %}</span>
					<span class="mdl-list__item-sub-title">
						{{ apks.0.apk.signature }}
					</span>
				</span>
			</li>
			{% endif %}
			<li class="mdl-list__item mdl-list__item--two-line">
				<span class="mdl-list__item-primary-content">
					<i class="material-icons mdl-list__item-icon">watch_later</i>
					<span>{% trans 'Added' %}</span>
					<span class="mdl-list__item-sub-title">
						{{ app.added_date|date:"SHORT_DATE_FORMAT" }}
					</span>
				</span>
			</li>
			<li class="mdl-list__item mdl-list__item--two-line">
				<span class="mdl-list__item-primary-content">
					<i class="material-icons mdl-list__item-icon">update</i>
					<span>{% trans 'Last Updated' %}</span>
					<span class="mdl-list__item-sub-title">
						{{ app.last_updated_date|naturaltime }} ({{ app.last_updated_date|date:"SHORT_DATE_FORMAT" }})
					</span>
				</span>
			</li>
		</ul>

		<p>
			<a href="{% url 'edit_app' app.repo.id app.id %}" class="rm-no-underline" style="margin-right:1em;">
				<button class="mdl-button mdl-js-button mdl-button--raised">
					<i class="material-icons">edit</i>
					{% trans 'Edit App Details' %}
				</button>
			</a>
			<a href="{% url 'screenshot_add' app.repo.id app.id %}" class="rm-no-underline" style="margin-right:1em;">
				<button class="mdl-button mdl-js-button mdl-button--raised">
					<i class="material-icons">add</i>
					{% trans 'Add Screenshot' %}
				</button>
			</a>
			<a href="{% url 'delete_app' app.repo.id app.id %}" class="rm-no-underline">
				<button class="mdl-button mdl-js-button mdl-button--raised">
					<i class="material-icons">delete</i>
					{% trans 'Delete App' %}
				</button>
			</a>
		</p>

	</div>

	<div class="mdl-cell mdl-cell--6-col">

		<h2>{% trans 'Versions' %}</h2>

		{% if apks %}
		<ul class="mdl-list">
			{% for pointer in apks %}
			<li>
				<h4>
					{{ pointer.apk.version_name }} <span style="font-weight: normal; font-size: 75%;">({{ pointer.apk.version_code }})</span>
				</h4>
				{% if pointer.file %}
				<ul class="mdl-list">
					<li class="mdl-list__item mdl-list__item--two-line">
						<span class="mdl-list__item-primary-content">
							<span>{% trans 'Size' %}</span>
							<span class="mdl-list__item-sub-title">
								{{ pointer.apk.size|filesizeformat }}
							</span>
						</span>
					</li>
					<li class="mdl-list__item mdl-list__item--two-line">
						<span class="mdl-list__item-primary-content">
							<span>{% trans 'File' %}</span>
							<span class="mdl-list__item-sub-title">
								{{ pointer.file.name }}
							</span>
						</span>
					</li>
					<li class="mdl-list__item mdl-list__item--two-line">
						<span class="mdl-list__item-primary-content">
							<span>
								{% blocktrans with type=pointer.apk.hash_type trimmed %}
								Hash ({{ type }})
								{% endblocktrans %}
							</span>
							<span class="mdl-list__item-sub-title">
								{{ pointer.apk.hash }}
							</span>
						</span>
					</li>
				</ul>
				{% else %}
				<em>{% trans 'APK is still downloading...' %}</em>
				{% endif %}
			</li>
			{% endfor %}
		</ul>
		{% endif %}

		<div style="text-align: right; margin: 2em;">
			<a href="{% url 'add_app' app.repo.id %}" class="mdl-cell mdl-cell--12-col rm-no-underline">
				<button class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored">
					<i class="material-icons">add</i>
				</button>
			</a>
		</div>

	</div>

	<div class="mdl-cell mdl-cell--12-col"
		 style="display: block; white-space: nowrap; overflow: auto; margin-right: 10px; margin-bottom: 10px; padding: 10px">
		{% for screenshot in app.screenshot_set.all %}
		<img src="{{ screenshot.get_url }}" style="display: inline-block; margin: 10px 0px 10px 10px; max-height:500px"/>
		<a href="{% url 'screenshot_delete' app.repo.id app.id screenshot.id %}" class="rm-no-underline"
		   style="position: relative; left: -25px;">
			<button class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored">
				<i class="material-icons">delete</i>
			</button>
		</a>
		{% endfor %}
	</div>

</div>

{% endblock rm-content %}

maker/templates/maker/app/remote_add.html
{% extends "../base.html" %}
{% load i18n %}
{% load sass_tags %}

{% block title %}{% trans 'Add App' %}{% endblock %}

{% block head %}
<link href="{% sass_src 'maker/css/forms.scss' %}" rel="stylesheet" type="text/css" media="all">
{% endblock head %}


{% block rm-content %}

<h1>{% blocktrans with app=app.name repo=repo.name %}Add {{ app }} to {{ repo }}{% endblocktrans %}</h1>

<div class="mdl-grid">

	<div class="mdl-cell mdl-cell--12-col">

		<h2 style="vertical-align: middle;">
			<img src="{{ app.icon.url }}" alt="Repo Icon" class="rm-icon"/> {{ app.name }}
		</h2>

		{% if app.summary %}
		<p>{{ app.summary }}</p>
		{% endif %}

		<p>{{ app.description|safe }}</p>
	</div>

	<div class="mdl-cell mdl-cell--12-col"
		 style="display: block; white-space: nowrap; overflow: auto; margin-right: 10px; margin-bottom: 10px; padding: 10px">
		{% for screenshot in app.remotescreenshot_set.all %}
		<img src="{{ screenshot.get_url }}" style="display: inline-block; margin: 10px 0px 10px 10px; max-height:500px"/>
		{% endfor %}
	</div>
</div>

<p></p>

<div class="rm-form">
	<form action="" enctype="multipart/form-data" method="post">
		{% csrf_token %}
		{% include '../form.html' %}
		<input type="submit" value="{% blocktrans with repo=repo.name %}Add App to {{ repo }}{% endblocktrans %}"/>
	</form>
</div>

<p></p>

{% endblock rm-content %}